[project]
name = "prietene"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "httpx>=0.28.1",
    "isort>=6.0.1",
    "langchain-openai>=0.3.31",
    "mcp-use>=1.3.10",
    "mcp[cli]>=1.13.1",
]
